name: AnnaSetu Automation Scheduler

on:
  schedule:
    # Runs every 10 minutes
    # - cron: "*/10 * * * *"

    # Runs every 2 minutes temporarily
    - cron: "*/2 * * * *"

  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger AnnaSetu Scheduler
        run: |
          curl -X POST \
            "${{ secrets.BACKEND_URL }}/automation/run" \
            -H "Authorization: Bearer ${{ secrets.AUTOMATION_SECRET }}"